import tkinter as tk
import tkinter.ttk as ttk
from tkinter import messagebox

main_win = tk.Tk()
main_win.title("テスト用ウィンドウ")
main_win.geometry("600x600")

# 画像読み込み
haruna = tk.PhotoImage(file="C:/Users/user/Desktop/新しい機能を学んでのコピーのコピーのコピー.png")
canvas = tk.Canvas(bg="black", width=1500, height=3000)
canvas.place(x=0, y=0)
canvas.create_image(0, 0, image=haruna, anchor=tk.NW)

# コンボボックスデータの一括定義
combo_data = [
    {
        "label": "クオリティ",
        "options": [
            "細部まで美しく描き込まれた",
            "超リアルな表現",
            "映画のようなライティング",
            "美しく仕上げられた",
            "緻密なディテール",
            "極限までリアル",
            "写真のようなリアリティ",
            "繊細な質感表現",
            "熟練の技で描かれた",
            "息をのむほどのクオリティ",
            "鮮やかな色彩",
            "卓越した技術",
            "鋭いフォーカス",
            "夢のような雰囲気",
            "洗練された仕上がり",
            "輝くような陰影",
            "鮮やかな色調",
            "ダイナミックな光演出",
            "なめらかなグラデーション",
            "優雅な構図",
            "クリスタルのような透明感",
            "非現実的なリアリズム",
            "深みのあるコントラスト",
            "滑らかな描画",
            "鮮明なイメージ表現",
            "完璧な完成度",
            "豊かに描き込まれた",
            "光沢感のある仕上がり",
            "芸術的な輝き",
            "自然なプロポーション",
            "表情豊かな筆遣い",
            "繊細な陰影",
            "生き生きとした質感",
            "印象的なビジュアル",
            "幻想的な光",
            "高解像度",
            "壮大な景観",
            "洗練されたアート技術",
            "微細なニュアンス",
            "圧倒的なリアリズム",
            "魔法のようなリアリズム",
            "透き通るような明瞭さ",
            "カラフルな色使い",
            "精密に作り込まれた",
            "自然な色や形の移行",
            "鮮やかなハイライト",
            "絵画的な質感",
            "自然な光の表現",
            "魅了されるディテール",
            "映画のような奥行き",
            "極限まで鋭いシャープさ",
            "濃密な色の彩度",
            "輝くような色彩",
            "生き生きとした表情",
            "深みのあるリアリズム",
            "光沢のある表面",
            "滑らかな融合",
            "空気感のあるライティング",
            "精密な線画",
            "純粋なビジュアル美",
            "写真クオリティの仕上がり",
            "感情の奥行き",
            "柔らかな光",
            "完璧なライティング",
            "調和の取れたバランス",
            "完璧な精密さ",
            "超細密なディテール",
            "空気感のあるリアリズム",
            "圧倒的な色の深み",
            "繊細に描き込まれた",
            "リアルな陰影表現",
            "現実離れしたディテール",
            "上品な光の使い方",
            "夢のように柔らかい質感",
            "荘厳な光",
            "劇的な光と影",
            "光り輝く雰囲気",
            "圧倒的なスケール感",
            "クリスタルのような質感",
            "超洗練された",
            "鮮やかな物語表現",
            "映画のような色補正",
            "自然な質感",
            "壮大なスタイル",
            "表情豊かなディテール",
            "贅沢な描写",
            "芸術的な繊細さ",
            "細部へのこだわり",
            "洗練された優雅さ",
            "ノスタルジックな雰囲気",
            "超洗練された",
            "幻想的な光の演出",
            "劇的な影",
            "美しいハイライト",
            "夕暮れ時の暖かな光",
            "超クリーンなライン",
            "魔法のようなビジュアル",
            "超高彩度な色彩",
            "活き活きとしたエネルギー",
            "驚くほどの輝き"
        ],
        "mapping": {
            "細部まで美しく描き込まれた": "highly detailed",
            "超リアルな表現": "ultra realistic",
            "映画のようなライティング": "cinematic lighting",
            "美しく仕上げられた": "beautifully rendered",
            "緻密なディテール": "intricate details",
            "極限までリアル": "hyper realistic",
            "写真のようなリアリティ": "photorealistic",
            "繊細な質感表現": "finely textured",
            "熟練の技で描かれた": "masterfully painted",
            "息をのむほどのクオリティ": "breathtaking quality",
            "鮮やかな色彩": "vivid colors",
            "卓越した技術": "exquisite craftsmanship",
            "鋭いフォーカス": "sharp focus",
            "夢のような雰囲気": "dreamlike atmosphere",
            "洗練された仕上がり": "polished finish",
            "輝くような陰影": "luminous shading",
            "鮮やかな色調": "vibrant tones",
            "ダイナミックな光演出": "dynamic lighting",
            "なめらかなグラデーション": "soft gradients",
            "優雅な構図": "elegant composition",
            "クリスタルのような透明感": "crystal clear",
            "非現実的なリアリズム": "surreal realism",
            "深みのあるコントラスト": "deep contrast",
            "滑らかな描画": "smooth rendering",
            "鮮明なイメージ表現": "vivid imagery",
            "完璧な完成度": "flawless execution",
            "豊かに描き込まれた": "richly detailed",
            "光沢感のある仕上がり": "glossy finish",
            "芸術的な輝き": "artistic brilliance",
            "自然なプロポーション": "realistic proportions",
            "表情豊かな筆遣い": "expressive brushwork",
            "繊細な陰影": "delicate shading",
            "生き生きとした質感": "lifelike textures",
            "印象的なビジュアル": "striking visuals",
            "幻想的な光": "ethereal glow",
            "高解像度": "high-resolution",
            "壮大な景観": "majestic scenery",
            "洗練されたアート技術": "refined artistry",
            "微細なニュアンス": "subtle nuances",
            "圧倒的なリアリズム": "intense realism",
            "魔法のようなリアリズム": "magical realism",
            "透き通るような明瞭さ": "pristine clarity",
            "カラフルな色使い": "colorful palette",
            "精密に作り込まれた": "finely crafted",
            "自然な色や形の移行": "smooth transitions",
            "鮮やかなハイライト": "vibrant highlights",
            "絵画的な質感": "painterly texture",
            "自然な光の表現": "natural lighting",
            "魅了されるディテール": "mesmerizing detail",
            "映画のような奥行き": "cinematic depth",
            "極限まで鋭いシャープさ": "ultra sharpness",
            "濃密な色の彩度": "deep color saturation",
            "輝くような色彩": "radiant colors",
            "生き生きとした表情": "vivid expressions",
            "深みのあるリアリズム": "profound realism",
            "光沢のある表面": "glossy surfaces",
            "滑らかな融合": "seamless blending",
            "空気感のあるライティング": "atmospheric lighting",
            "精密な線画": "intricate linework",
            "純粋なビジュアル美": "pure visual beauty",
            "写真クオリティの仕上がり": "photo-grade finish",
            "感情の奥行き": "emotional depth",
            "柔らかな光": "soft glow",
            "完璧なライティング": "perfect lighting",
            "調和の取れたバランス": "harmonious balance",
            "完璧な精密さ": "immaculate precision",
            "超細密なディテール": "hyperfine detail",
            "空気感のあるリアリズム": "atmospheric realism",
            "圧倒的な色の深み": "intense color depth",
            "繊細に描き込まれた": "delicately detailed",
            "リアルな陰影表現": "realistic shading",
            "現実離れしたディテール": "surreal detail",
            "上品な光の使い方": "elegant lighting",
            "夢のように柔らかい質感": "dreamy softness",
            "荘厳な光": "majestic lighting",
            "劇的な光と影": "dramatic lighting",
            "光り輝く雰囲気": "luminous atmosphere",
            "圧倒的なスケール感": "epic scale",
            "クリスタルのような質感": "crystal textures",
            "超洗練された": "super refined",
            "鮮やかな物語表現": "vivid storytelling",
            "映画のような色補正": "cinematic color grading",
            "自然な質感": "natural textures",
            "壮大なスタイル": "grandiose style",
            "表情豊かなディテール": "expressive detail",
            "贅沢な描写": "luxurious rendering",
            "芸術的な繊細さ": "artistic finesse",
            "細部へのこだわり": "meticulous detailing",
            "洗練された優雅さ": "refined elegance",
            "ノスタルジックな雰囲気": "nostalgic atmosphere",
            "幻想的な光の演出": "fantastical lighting",
            "劇的な影": "dramatic shadows",
            "美しいハイライト": "beautiful highlights",
            "夕暮れ時の暖かな光": "golden hour glow",
            "超クリーンなライン": "ultra clean lines",
            "魔法のようなビジュアル": "enchanted visuals",
            "超高彩度な色彩": "hyper-saturated colors",
            "活き活きとしたエネルギー": "lively energy",
            "驚くほどの輝き": "stunning brilliance"
        },
        "add_comma": False
    },
    {
        "label": "キャラ1",
        "options": [
            "少年",
            "少女",
            "青年男性",
            "青年女性",
            "中年男性",
            "中年女性",
            "高齢男性",
            "高齢女性",
            "ビジネスマン",
            "ビジネスウーマン",
            "学生",
            "小学校教師",
            "大学教授",
            "医者",
            "看護師",
            "警察官",
            "消防士",
            "科学者",
            "アスリート",
            "バレリーナ",
            "ロックミュージシャン",
            "ジャズシンガー",
            "演劇俳優",
            "映画監督",
            "写真家",
            "パイロット",
            "キャビンアテンダント",
            "シェフ",
            "パティシエ",
            "農家",
            "漁師",
            "工場労働者",
            "ソフトウェアエンジニア",
            "グラフィックデザイナー",
            "建築家",
            "探偵",
            "弁護士",
            "裁判官",
            "政治家",
            "ジャーナリスト",
            "書店員",
            "カフェ店員",
            "花屋店員",
            "美容師",
            "メイクアップアーティスト",
            "モデル",
            "ファッションデザイナー",
            "宝石商",
            "お菓子屋さん",
            "ウェイター",
            "ウェイトレス",
            "サラリーマン",
            "OL（オフィスレディ）",
            "ニート",
            "主婦",
            "主夫",
            "保育士",
            "動物看護師",
            "獣医師",
            "バーテンダー",
            "漫画家",
            "小説家",
            "イラストレーター",
            "アニメーター",
            "声優",
            "ラジオパーソナリティ",
            "通訳者",
            "翻訳家",
            "ヨガインストラクター",
            "フィットネストレーナー",
            "サッカー選手",
            "バスケットボール選手",
            "テニスプレイヤー",
            "ゴルファー",
            "レーサー",
            "スキー選手",
            "プロゲーマー",
            "ストリーマー",
            "SNSインフルエンサー",
            "ブロガー",
            "縁日屋台店員",
            "着物職人",
            "伝統芸能師",
            "剣道家",
            "柔道家",
            "空手家",
            "武道家",
            "書道家",
            "茶道家",
            "華道家",
            "旅行ガイド",
            "バックパッカー",
            "冒険家",
            "山岳ガイド",
            "ライフセーバー",
            "環境活動家",
            "ボランティア",
            "NGOスタッフ",
            "料理研究家",
            "お笑い芸人"
        ],
        "mapping": {
            "少年": "young boy",
            "少女": "young girl",
            "青年男性": "young man",
            "青年女性": "young woman",
            "中年男性": "middle-aged man",
            "中年女性": "middle-aged woman",
            "高齢男性": "elderly man",
            "高齢女性": "elderly woman",
            "ビジネスマン": "businessman",
            "ビジネスウーマン": "businesswoman",
            "学生": "student",
            "小学校教師": "elementary school teacher",
            "大学教授": "university professor",
            "医者": "doctor",
            "看護師": "nurse",
            "警察官": "police officer",
            "消防士": "firefighter",
            "科学者": "scientist",
            "アスリート": "athlete",
            "バレリーナ": "ballerina",
            "ロックミュージシャン": "rock musician",
            "ジャズシンガー": "jazz singer",
            "演劇俳優": "stage actor",
            "映画監督": "film director",
            "写真家": "photographer",
            "パイロット": "pilot",
            "キャビンアテンダント": "flight attendant",
            "シェフ": "chef",
            "パティシエ": "pastry chef",
            "農家": "farmer",
            "漁師": "fisherman",
            "工場労働者": "factory worker",
            "ソフトウェアエンジニア": "software engineer",
            "グラフィックデザイナー": "graphic designer",
            "建築家": "architect",
            "探偵": "detective",
            "弁護士": "lawyer",
            "裁判官": "judge",
            "政治家": "politician",
            "ジャーナリスト": "journalist",
            "書店員": "bookstore clerk",
            "カフェ店員": "cafe staff",
            "花屋店員": "florist",
            "美容師": "hair stylist",
            "メイクアップアーティスト": "makeup artist",
            "モデル": "model",
            "ファッションデザイナー": "fashion designer",
            "宝石商": "jeweler",
            "お菓子屋さん": "confectioner",
            "ウェイター": "waiter",
            "ウェイトレス": "waitress",
            "サラリーマン": "office worker",
            "OL（オフィスレディ）": "office lady",
            "ニート": "unemployed youth",
            "主婦": "housewife",
            "主夫": "househusband",
            "保育士": "nursery teacher",
            "動物看護師": "veterinary nurse",
            "獣医師": "veterinarian",
            "バーテンダー": "bartender",
            "漫画家": "manga artist",
            "小説家": "novelist",
            "イラストレーター": "illustrator",
            "アニメーター": "animator",
            "声優": "voice actor",
            "ラジオパーソナリティ": "radio host",
            "通訳者": "interpreter",
            "翻訳家": "translator",
            "ヨガインストラクター": "yoga instructor",
            "フィットネストレーナー": "fitness trainer",
            "サッカー選手": "soccer player",
            "バスケットボール選手": "basketball player",
            "テニスプレイヤー": "tennis player",
            "ゴルファー": "golfer",
            "レーサー": "race car driver",
            "スキー選手": "skier",
            "プロゲーマー": "pro gamer",
            "ストリーマー": "streamer",
            "SNSインフルエンサー": "social media influencer",
            "ブロガー": "blogger",
            "縁日屋台店員": "festival stall vendor",
            "着物職人": "kimono craftsman",
            "伝統芸能師": "traditional performer",
            "剣道家": "kendo practitioner",
            "柔道家": "judo practitioner",
            "空手家": "karate practitioner",
            "武道家": "martial artist",
            "書道家": "calligrapher",
            "茶道家": "tea ceremony master",
            "華道家": "flower arrangement master",
            "旅行ガイド": "tour guide",
            "バックパッカー": "backpacker",
            "冒険家": "adventurer",
            "山岳ガイド": "mountain guide",
            "ライフセーバー": "lifeguard",
            "環境活動家": "environmental activist",
            "ボランティア": "volunteer worker",
            "NGOスタッフ": "NGO worker",
            "料理研究家": "culinary researcher",
            "お笑い芸人": "comedian"
        },
        "add_comma": True
    }
]




comboboxes = []
selected_flags = []

# コンボボックスの作成（2列構成・幅指定）
def on_select(index):
    selected_flags[index] = True

for i, data in enumerate(combo_data):
    values = [data["label"]] + data["options"]
    row = i % 12 + 12
    col = i // 12
    cb = ttk.Combobox(main_win, values=values, width=20)
    cb.grid(row=row, column=col, padx=10, pady=5)
    cb.set(values[0])
    cb.bind("<<ComboboxSelected>>", lambda e, idx=i: on_select(idx))
    comboboxes.append(cb)
    selected_flags.append(False)

def print_text():
    result = []
    for i, cb in enumerate(comboboxes):
        if selected_flags[i]:
            selected = cb.get()
            if selected in combo_data[i]["mapping"]:
                value = combo_data[i]["mapping"][selected]
                if combo_data[i]["add_comma"]:
                    value = "," + value
                result.append(value)
    label.config(text="".join(result))

def copy_text():
    text_to_copy = label.cget("text")
    main_win.clipboard_clear()
    main_win.clipboard_append(text_to_copy)
    messagebox.showinfo("コピー完了", "テキストがコピーされました。")

button_print = tk.Button(main_win, text="表示", command=print_text)
button_print.grid(row=0, column=1, padx=10)

button_copy = tk.Button(main_win, text="コピー", command=copy_text)
button_copy.grid(row=0, column=0, padx=10)

label = tk.Label(main_win)
label.grid(row=2, column=0, columnspan=2, pady=5)

main_win.mainloop()


